name: ci

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-slim
    name: test
    steps:
      - uses: actions/checkout@v6

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Build
        run: zig build

      - name: Test
        run: zig build test

      - name: Examples
        run: zig build examples

  cross-compile:
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-linux-gnu
          - aarch64-linux-gnu
          - x86_64-macos
          - aarch64-macos
          - x86_64-windows-gnu
          - aarch64-windows-gnu
          - wasm32-freestanding

    runs-on: ubuntu-slim
    name: ${{ matrix.target }}

    steps:
      - uses: actions/checkout@v6

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Build
        run: zig build lib -Dtarget=${{ matrix.target }}
